name: list_manager
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/dubey2k/list_manager.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chips_choice: ^2.0.1
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  provider: ^6.0.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
