name: list_manager
description: A package which helps you managing lists in flutter. It provide
  Paging, Filtering, Searching, Filtering + Paging, Searching + Paging,
  Searching, + Filtering + Paging.
version: 2.1.0
homepage: https://github.com/dubey2k/list_manager.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  chips_choice: ^2.0.1
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  intl: ^0.19.0
  provider: ^6.0.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter: null
