name: list_manager
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/dubey2k/list_manager.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chips_choice: ^2.0.1
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  provider: ^6.0.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
